/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz1sistemasg2;

public class App {
    

    public static void main(String[] args) {
    }

    /*  Implemente una funcion llamada calcularValorHora que cumpla con las siguientes caracteristicas
        * Recibe: 
            - Una cadena de caracteres que representa el tipo de vehiculo (C, M o B)
            - Un entero que representa la cantidad de horas de permanencia
        * Retorna:
            - Un entero representando el valor total de las boletas
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
        public static int calcularValorHora(String tipoVehiculo, int horasDePermanencia) {
            
            try {

            double Carro = 5000;
            double Moto = 3000;
            double Bicicleta = 1000;
            int valorTotalHoras = 0;
            int valorTotalExtra = 0;
            int horasExtra = 0;
            int valorHorasDescuento = 0;

                switch (tipoVehiculo) {
                    case "C":

                    valorTotalHoras = (int)(horasDePermanencia * Carro);
                    break;

                    case "M":

                    valorTotalHoras = (int)(horasDePermanencia * Moto);
                    break;

                    case "B":
                    valorTotalHoras = (int)(horasDePermanencia * Bicicleta);
                    break;
                
                    default:
                    break;
                }
                
                if (horasDePermanencia <= 0)
                    return -1;
                    
                else if (horasDePermanencia > 3)

                    horasExtra = (horasDePermanencia - 3);
                    valorTotalExtra = valorTotalHoras + (horasExtra * 2000);
                    return valorTotalExtra;
                 
                } 
                catch (Exception e) {
                     return -1;
            }

        
    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularDescuento que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando la si es estudiante o no
            - Un entero represenatando la cantidad de horas
        * Retorna:
            - Un entero representando el valor del descuento
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    
        public static int calcularDescuento(int valorTotalH, int estudiante, int cantidadHoras){

            try {

                int ValorDescuento = 0;
            
                ValorDescuento = (int)(valorTotalH * 0.3);
                return ValorDescuento;
            }



            } catch (Exception e) {
                return -1;
            }

        }

    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularFactura que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando el valor del descuento
        * Retorna:
            - Un entero representando el valor del total de la factura incluyendo el iva
    */
    //------------------------------------------------------------------
    


    //------------------------------------------------------------------
}

